order:
  - 1. Linearity of Expectance
  - 2. Variance of Sum
  - 3. Discrete Probability Practice
  - 4. Maximal Likelihood of Normal Distribution
  - 5. Maximal Likelihood of Multivariate Normal Distribution
