type: order_cards
visible: false
header: Variance of Sum
text: Order the cards to reconstruct variance of sum proof
shuffle: true
score: 2
quiz:
  variants:
    - text: |
        Now consider $$\mathbb V (a \xi + b \eta)$$
    - text: |
        Simplifying the expression above, we will get:
        $$\mathbb V \xi = \mathbb E \xi^2 - (\mathbb E \xi)^2$$
    - text: >
        In fact, $\mathbb E \xi$ is a constant (as it is kind of average value),
        thus:

        $$\mathbb V \xi = \mathbb E \xi^2 - 2 (\mathbb E \xi)^2 + (\mathbb E
        \xi)^2$$
    - text: >
        Opening the brackets, we will get:

        $$\mathbb V (a \xi + b \eta) =\mathbb E (a^2 \xi^2) + \mathbb E (2 a \xi
        b \eta) + \mathbb E (b \eta)^2 - (\mathbb E (a \xi))^2 - 2 \mathbb E a
        \xi \mathbb E b \eta - (\mathbb E (b \eta))^2$$
    - text: |
        Start with definition of $\mathbb V \xi$,
        $$\mathbb V \xi = \mathbb E (\xi - \mathbb E \xi)^2$$
    - text: >
        Take the formula that was proven above, and we will get:

        $$\mathbb V (a \xi + b \eta) =\mathbb E (a \xi + b \eta)^2 - (\mathbb E
        (a \xi + b \eta))^2$$
    - text: >
        If we have independent $\xi$ and $\eta$, then

        $$\mathbb E \xi \eta = \sum_{k} x_k y_k p(x_k, y_k) = \sum_{k} x_k y_k
        p(x_k)p(y_k) = \sum_{k} x_k p(x_k) \sum_{k} y_k p(y_k) = \mathbb E \xi
        \mathbb E \eta$$
    - text: |
        In that case the two last terms are cancelled, and we get:
        $$\mathbb V (a \xi + b \eta) = a^2 \mathbb V \xi + b^2 \mathbb V \eta$$
    - text: >
        Taking out the coefficients, we get:

        $$\mathbb V (a \xi + b \eta) = a^2 \mathbb E \xi^2 +2 a b \mathbb
        E  (\xi \eta) + b^2 \mathbb E \eta^2 - a^2 (\mathbb E \xi)^2 - 2 a b
        \mathbb E \xi \mathbb E \eta - b^2(\mathbb E \eta)^2$$
    - text: >
        Opening the brackets and thinking about $\mathbb E$ as about the
        average, we will get:

        $$\mathbb V \xi = \mathbb E (\xi^2 - 2 \xi \mathbb E \xi + (\mathbb E
        \xi)^2)$$
    - text: |
        Note that this expression is correct for any $\xi$ !!!
    - text: >
        Recalling that $\mathbb V \xi = \mathbb E \xi^2 - (\mathbb E \xi)^2$:

        $$\mathbb V (a \xi + b \eta) = a^2 \mathbb V \xi + b^2 \mathbb V \eta +
        2 a b \mathbb E  (\xi \eta) - 2 a b \mathbb E \xi \mathbb E \eta$$
answer:
  - a87ff679a2f3e71d9181a67b7542122c
  - 45c48cce2e2d7fbdea1afc51c7c6ad26
  - c81e728d9d4c2f636f067f89cc14862c
  - c4ca4238a0b923820dcc509a6f75849b
  - d3d9446802a44259755d38e6d163e820
  - cfcd208495d565ef66e7dff9f98764da
  - e4da3b7fbbce2345d7772b0674a318d5
  - eccbc87e4b5ce2fe28308fd9f2a7baf3
  - c9f0f895fb98ab9159f51fd0297e236d
  - 6512bd43d9caa6e02c990b0a82652dca
  - 1679091c5a880faf6fb5e6087eb1b2dc
  - 8f14e45fceea167a5a36dedd4bea2543
